In [12]:
import torch

Create a random tensor: 3 * 3 tensor as float

In [16]:
rand_tensor_float = torch.rand((3, 3),dtype=torch.float32)
rand_tensor_float

tensor([[0.4342, 0.2046, 0.8137],
        [0.5839, 0.2912, 0.7296],
        [0.7108, 0.8108, 0.5510]])

Create a random tensor: 4 * 4 tensor as double

In [17]:
rand_tensor_double = torch.rand((4, 4),dtype=torch.double)
rand_tensor_double

tensor([[0.5645, 0.9161, 0.8644, 0.1569],
        [0.6758, 0.7489, 0.6715, 0.7842],
        [0.8308, 0.6426, 0.3213, 0.5986],
        [0.3498, 0.9398, 0.2786, 0.5466]], dtype=torch.float64)

Create a random tensor:  5 * 3 * 4 tensor as short type

In [18]:
rand_tensor_short = torch.randint(100,(5, 3,4),dtype=torch.short)
rand_tensor_short

tensor([[[39, 63, 90, 30],
         [57, 97, 41, 62],
         [96, 17, 40, 26]],

        [[70, 80, 72, 48],
         [14, 63, 11, 49],
         [47, 81, 21, 76]],

        [[ 0, 82, 96, 14],
         [28, 74, 11, 79],
         [44, 95, 66, 98]],

        [[79, 30, 49, 36],
         [61, 75, 36, 93],
         [39, 56, 40, 75]],

        [[50, 92, 43, 61],
         [20, 73, 28, 88],
         [49, 49, 67,  8]]], dtype=torch.int16)

Change elements in the GPU

In [79]:
rand_tensor_float.cuda()
rand_tensor_double.cuda()
rand_tensor_short.cuda()

Display the order of elements and its transpose in the memory then use storage offset and contiguous:

In [67]:
print(rand_tensor_float.storage())
print(rand_tensor_float.storage_offset())
print(rand_tensor_float.contiguous())

 0.8009039759635925
 0.141163170337677
 0.12127053737640381
 0.18267393112182617
 0.5612189769744873
 0.04778707027435303
 0.5900092720985413
 0.8854416608810425
 0.8316203951835632
[torch.FloatStorage of size 9]
0
tensor([[0.8009, 0.1412, 0.1213],
        [0.1827, 0.5612, 0.0478],
        [0.5900, 0.8854, 0.8316]])


In [94]:
rand_tensor_float_t=rand_tensor_float.t()
print(rand_tensor_float_t.storage())
print(rand_tensor_float_t.storage_offset())
print(rand_tensor_float_t.contiguous())

 0.8009039759635925
 0.141163170337677
 0.12127053737640381
 0.18267393112182617
 0.5612189769744873
 0.04778707027435303
 0.5900092720985413
 0.8854416608810425
 0.8316203951835632
[torch.FloatStorage of size 9]
0
tensor([[0.8009, 0.1827, 0.5900],
        [0.1412, 0.5612, 0.8854],
        [0.1213, 0.0478, 0.8316]])


In [65]:
print(rand_tensor_double.storage())
print(rand_tensor_double.storage_offset())
print(rand_tensor_double.contiguous())

 0.775733305705393
 0.6383104187169981
 0.5291102053915608
 0.06959019267742872
 0.5981132952869858
 0.022468670203133145
 0.8094413320501909
 0.2542800493231827
 0.6257892479618693
 0.6113720711029355
 0.5371115658848371
 0.8009418147578846
 0.16510809722712172
 0.2665173831710238
 0.29609008894321476
 0.6892442343441633
[torch.DoubleStorage of size 16]
0
tensor([[0.7757, 0.6383, 0.5291, 0.0696],
        [0.5981, 0.0225, 0.8094, 0.2543],
        [0.6258, 0.6114, 0.5371, 0.8009],
        [0.1651, 0.2665, 0.2961, 0.6892]], dtype=torch.float64)


In [95]:
rand_tensor_double_t=rand_tensor_double.t()
print(rand_tensor_double_t.storage())
print(rand_tensor_double_t.storage_offset())
print(rand_tensor_double_t.contiguous())

 0.775733305705393
 0.6383104187169981
 0.5291102053915608
 0.06959019267742872
 0.5981132952869858
 0.022468670203133145
 0.8094413320501909
 0.2542800493231827
 0.6257892479618693
 0.6113720711029355
 0.5371115658848371
 0.8009418147578846
 0.16510809722712172
 0.2665173831710238
 0.29609008894321476
 0.6892442343441633
[torch.DoubleStorage of size 16]
0
tensor([[0.7757, 0.5981, 0.6258, 0.1651],
        [0.6383, 0.0225, 0.6114, 0.2665],
        [0.5291, 0.8094, 0.5371, 0.2961],
        [0.0696, 0.2543, 0.8009, 0.6892]], dtype=torch.float64)


In [66]:
print(rand_tensor_short.storage())
print(rand_tensor_short.storage_offset())
print(rand_tensor_short.contiguous())

 26
 19
 20
 14
 3
 4
 9
 15
 70
 47
 92
 94
 57
 56
 54
 99
 47
 97
 88
 66
 79
 15
 75
 20
 40
 75
 32
 67
 20
 78
 65
 83
 27
 69
 57
 21
 44
 10
 63
 15
 81
 51
 48
 24
 0
 30
 72
 88
 98
 1
 55
 43
 8
 11
 42
 84
 44
 70
 79
 80
[torch.ShortStorage of size 60]
0
tensor([[[26, 19, 20, 14],
         [ 3,  4,  9, 15],
         [70, 47, 92, 94]],

        [[57, 56, 54, 99],
         [47, 97, 88, 66],
         [79, 15, 75, 20]],

        [[40, 75, 32, 67],
         [20, 78, 65, 83],
         [27, 69, 57, 21]],

        [[44, 10, 63, 15],
         [81, 51, 48, 24],
         [ 0, 30, 72, 88]],

        [[98,  1, 55, 43],
         [ 8, 11, 42, 84],
         [44, 70, 79, 80]]], dtype=torch.int16)


In [97]:
rand_tensor_short_t=rand_tensor_short.transpose(1,0)
print(rand_tensor_short_t.storage())
print(rand_tensor_short_t.storage_offset())
print(rand_tensor_short_t.contiguous())

 26
 19
 20
 14
 3
 4
 9
 15
 70
 47
 92
 94
 57
 56
 54
 99
 47
 97
 88
 66
 79
 15
 75
 20
 40
 75
 32
 67
 20
 78
 65
 83
 27
 69
 57
 21
 44
 10
 63
 15
 81
 51
 48
 24
 0
 30
 72
 88
 98
 1
 55
 43
 8
 11
 42
 84
 44
 70
 79
 80
[torch.ShortStorage of size 60]
0
tensor([[[26, 19, 20, 14],
         [57, 56, 54, 99],
         [40, 75, 32, 67],
         [44, 10, 63, 15],
         [98,  1, 55, 43]],

        [[ 3,  4,  9, 15],
         [47, 97, 88, 66],
         [20, 78, 65, 83],
         [81, 51, 48, 24],
         [ 8, 11, 42, 84]],

        [[70, 47, 92, 94],
         [79, 15, 75, 20],
         [27, 69, 57, 21],
         [ 0, 30, 72, 88],
         [44, 70, 79, 80]]], dtype=torch.int16)


Save and load one among the elements of tensors using the torch:

In [33]:
with open("double_tensor.t",'wb') as f:
    torch.save(rand_tensor_double, f)
with open("double_tensor.t",'rb') as f:
    points = torch.load(f)

Save and load one among the elements of tensors using the h5py file:

In [38]:
import h5py
f = h5py.File('float_tensor.hdf5', 'w')
dset = f.create_dataset('randompoints', data=points.numpy())
f.close()

In [45]:
f = h5py.File('float_tensor.hdf5', 'r')
ds = f['randompoints']
ds[:]

array([[0.56445116, 0.9160951 , 0.86437304, 0.15693904],
       [0.67579893, 0.74889005, 0.67148646, 0.78424981],
       [0.83082425, 0.6426273 , 0.32130759, 0.59857934],
       [0.34977857, 0.93983639, 0.2786402 , 0.5466177 ]])

The different true and false requires_grad values in Autograd:

In [72]:
x=torch.rand((2,2))
y=torch.rand((2,2),requires_grad=True)
z=torch.rand((2,2))

In [76]:
a=x+y
a.requires_grad

True

In [77]:
b=x+z

In [78]:
b.requires_grad

False